name = "sevimli-aile-api"
compatibility_date = "2024-10-01"

[vars]
FIREBASE_API_KEY = "AIzaSyCjyLtc5VlLmOY2C-SGKloabi6hpDhLM9Q"
FIREBASE_PROJECT_ID = "sevimli-aile"
ADMIN_EMAIL = "islammuradov1@icloud.com"
YOUTUBE_API_KEY = ""
FRONTEND_ORIGIN = "https://sevimliaile.pages.dev"
FIREBASE_AUTH_DOMAIN = "sevimli-aile.firebaseapp.com"
FIREBASE_APP_ID = "1:955131925025:web:9f17280e385a2f6ee64960"

[[d1_databases]]
binding = "DB"
database_name = "sevimli-aile"
database_id = ""

[[r2_buckets]]
binding = "R2"
bucket_name = "sevimli-aile-exports"
